### ISSUE TITLE
Missing Information In Linux- In Depth Guide

### ISSUE THREAD

**Issue by starlap** [donejs/donejs#657]
> **This is probably a bug with the code highlighting breaking or taking too long.  Perhaps we should throttle it**

**Environment:**
Ubuntu 16.04 LTS
Firefox

**Missing Pieces of Highlighted Instructions While in Linux**

**Explanation:**
Several of the highlight boxes are missing instructions.

1) **Go to** [Building to iOS and Android](https://donejs.com/place-my-order.html#section=section_BuildingtoiOSandAndroid)

![buildingtoios_missing_highlight](https://cloud.githubusercontent.com/assets/18269875/14966485/80cb126a-1067-11e6-8e86-2d347c789374.png)

2) **Go to** [AJAX](https://donejs.com/place-my-order.html#section=section_BuildingtoiOSandAndroid__AJAX)

![ajax_missing_highlight](https://cloud.githubusercontent.com/assets/18269875/14965708/b2040b42-1063-11e6-8ed4-68aa56f9012e.png)

3) **Go to** [Building to NW.js](https://donejs.com/place-my-order.html#section=section_BuildingtoNW_js)

![buildingtonw_missing_highlight](https://cloud.githubusercontent.com/assets/18269875/14965849/6b468396-1064-11e6-8b53-f9d894579c21.png)

4) **Go to** [Bundling Assets](https://donejs.com/place-my-order.html#section=section_Bundlingassets)

![bundlingassets_missing_highlight](https://cloud.githubusercontent.com/assets/18269875/14965910/bf76bb20-1064-11e6-82f3-57eca6f3bb90.png)

5) **Go to** [Configuring DoneJS](https://donejs.com/place-my-order.html#section=section_StatichostingonFirebase__ConfiguringDoneJS)

![configuringdonejs_missing_highlight](https://cloud.githubusercontent.com/assets/18269875/14965953/0b488e2a-1065-11e6-8d9f-fd2ed3098063.png)

6) **Go to** [Continuous Deployment](https://donejs.com/place-my-order.html#section=section_ContinuousDeployment)

![continuousdeployment_missing_highlight](https://cloud.githubusercontent.com/assets/18269875/14966042/633f0f3c-1065-11e6-973f-88bb60a015dc.png)

**Comment by daffl** [comment]
I can't reproduce on my virtual machine (but was able to before the fix). Did you clear the browser cache? This is what I am seeing in Ubuntu 15.04 on Chrome:

![screen shot 2016-05-02 at 1 23 23 pm](https://cloud.githubusercontent.com/assets/338316/14966843/4942630a-1069-11e6-8a23-69ef5fb3bf4a.png)
![screen shot 2016-05-02 at 1 22 38 pm](https://cloud.githubusercontent.com/assets/338316/14966844/4947a5c2-1069-11e6-9a06-09517d2d15d2.png)

**Comment by starlap** [comment]
Some of them appear to be cleared but I'm still seeing missing pieces.  I am on Ubuntu 16.04 Chrome.  This is a gif that shows my browser cache cleared and still seeing missing highlight boxes:

![missing info w cache clear](https://cloud.githubusercontent.com/assets/18269875/14968366/306cb74c-1071-11e6-838f-f7b3a05c3f27.gif)

**Comment by daffl** [comment]
I just published another change which seems to be working for me on my VM and in Browserstack. Can you double check please?

**Comment by starlap** [comment]
Hi David!  Sorry, I'm only in on Mondays and Fridays, so just now seeing this.  
Unfortunately, I'm still seeing some areas where info is missing, though it seems to have cleared up some of the issues.  This is some of what I'm seeing on Chrome with my cache cleared:

**Missing Info**
![4 6_missing info](https://cloud.githubusercontent.com/assets/18269875/15082908/444a4692-137f-11e6-8e97-d662e3e0f6b9.png)

**MIssing Info**
![4 6_missing info_travis](https://cloud.githubusercontent.com/assets/18269875/15082919/4b3d0f66-137f-11e6-9824-6d4a7c135bd0.png)

**MIssing Info**
![4 6_missing info_view model](https://cloud.githubusercontent.com/assets/18269875/15082928/519100de-137f-11e6-89c8-462e3e1e7ad7.png)

There are more missing pieces but I don't know if it's helpful to list them all.  If so, I'll go in and grab them.

**Comment by justinbmeyer** [comment]
Probably closed by: https://github.com/donejs/donejs/issues/708
